[colors.primary]
background = "#0f1010"  # Темно-серый (фон)
foreground = "#b9bed2"  # Светло-серый (текст)

[colors.normal]
black   = "#1C2526"  # Черный/темный
red     = "#3B6EA8"  # Синий с оттенком
green   = "#4D87B6"  # Светлее синий
yellow  = "#5FA0C4"  # Еще светлее
blue    = "#72B9D2"  # Яркий синий
magenta = "#85D2E0"  # Светло-голубой
cyan    = "#98EBEE"  # Очень светлый
white   = "#B0F0F4"  # Почти белый

[colors.bright]
black   = "#4D5D64"  # Темно-серый
red     = "#3B6EA8"  # Повтор синий
green   = "#4D87B6"  # Повтор светлее
yellow  = "#5FA0C4"  # Повтор еще светлее
blue    = "#72B9D2"  # Повтор яркий
magenta = "#85D2E0"  # Повтор светло-голубой
cyan    = "#98EBEE"  # Повтор очень светлый
white   = "#B0F0F4"  # Повтор почти белый

[font.normal]
family = "JetBrainsMono NF"
